block-list-secret-scan: []
branch: master
directory:
  - .
download-external-modules: true
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
  - all
mask: []
quiet: true
secrets-history-timeout: 12h
secrets-scan-file-type: []
skip-check:
  - CKV_K8S_21
  - CKV_K8S_10
  - CKV_K8S_11
  - CKV_K8S_12 #  "Memory requests should be set"
  - CKV_K8S_13 # "Memory limits should be set"
  - CKV_K8S_43
  - CKV_K8S_15 # "Image Pull Policy should be Always"
  # Improve these
  - CKV_K8S_9
  - CKV_K8S_8
  - CKV_K8S_35 # "Prefer using secrets as files over secrets as environment variables"

summary-position: top
